services:
  web:
    image: portfolio:latest
    container_name: portfolio
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      - my-net

networks:
  my-net: