services:
  web:
    image: portfolio:latest
    container_name: portfolio
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      - reverse-proxy-net

networks:
  reverse-proxy-net:
    external: true
